version: "3.8"

x-bot: &bot
  BOT_TOKEN: $BOT_TOKEN

x-mysql: &mysql
  MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  MYSQL_PASSWORD: $MYSQL_PASSWORD
  MYSQL_HOSTNAME: $MYSQL_HOSTNAME
  MYSQL_PORT: $MYSQL_PORT
  MYSQL_DATABASE: $MYSQL_DATABASE
  REAL_MESSAGES_TABLE: $REAL_MESSAGES_TABLE
  MYSQL_USER: $MYSQL_USER

services:
  bot:
    build: ./src/bot/.
    restart: always
    environment:
      <<: *bot
      <<: *mysql
    volumes:
      - ./src/bot/code:/app

  mysql:
    image: mysql:8.0.22
    restart: always
    environment:
      <<: *mysql
    ports:
      - 3306:3306
    volumes:
      - ./src/mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
